package m1.entity;
// Generated 10 mai 2015 22:43:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String name;
     private String description;
     private Set userGroups = new HashSet(0);

    public Group() {
    }

	
    public Group(User user, String name) {
        this.user = user;
        this.name = name;
    }
    public Group(User user, String name, String description, Set userGroups) {
       this.user = user;
       this.name = name;
       this.description = description;
       this.userGroups = userGroups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(Set userGroups) {
        this.userGroups = userGroups;
    }




}


